-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 17:58:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET NAMES 'utf8';
-- -----------------------------------------------------
-- Table `vmski`.`PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERSON` (
  `personid` INT NOT NULL AUTO_INCREMENT,
  `fornavn` VARCHAR(45) NOT NULL,
  `etternavn` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `postnr` CHAR(4) NOT NULL,
  `poststed` VARCHAR(45) NOT NULL,
  `telefonnr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`personid`))
ENGINE = InnoDB DEFAULT CHARSET=latin1;

-- -----------------------------------------------------
-- Table `vmski`.`ØVELSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ØVELSE` (
  `øvelseid` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `dato` VARCHAR(45) NOT NULL,
  `sted` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`øvelseid`)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `vmski`.`PUBLIKUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIKUM (
  publikumid INT NOT NULL AUTO_INCREMENT,
  billetttype VARCHAR(45) NOT NULL,
  personid INT NOT NULL,
  PRIMARY KEY (publikumid),
  CONSTRAINT fk_PUBLIKUM_PERSON1
    FOREIGN KEY (personid)
    REFERENCES PERSON (personid)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;
-- Table `vmski`.`OPPMELDING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPPMELDING` (
  `oppmeldingsnummer` INT NOT NULL AUTO_INCREMENT,
  `øvelseid` INT NOT NULL,
  `personid` INT NOT NULL,
  PRIMARY KEY (`oppmeldingsnummer`),
  CONSTRAINT `personid`
    FOREIGN KEY (`personid`)
    REFERENCES `PERSON` (`personid`),
  CONSTRAINT `øvelseid`
    FOREIGN KEY (`øvelseid`)
    REFERENCES `ØVELSE` (`øvelseid`)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;

-- Table vmski.`UTØVER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS UTØVER (
  utøverid INT NOT NULL AUTO_INCREMENT,
  nasjonalitet VARCHAR(45) NOT NULL,
  personid INT NOT NULL,
  PRIMARY KEY (utøverid),
  CONSTRAINT fk_UTØVER_PERSON1
    FOREIGN KEY (personid)
    REFERENCES PERSON (personid)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;
-- -----------------------------------------------------
-- Insert `vmski`.`Øvelse`
-- -----------------------------------------------------
INSERT INTO `øvelse`(`type`, `dato`, `sted`) 
VALUES ('Langrenn','2018-08-24','Oslo'),
 ('Slalom','2015-03-13','Bergen'),
 ('Skihopp','2017-08-24','Kristiandsand'),
 ('Akebrettstafett','2018-03-08','Jessheim');